version: '3.9'

services:
  app:
    container_name: ${APP_NAME}-app
    build:
      context: ./docker/php
      network: host

    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
    working_dir: /var/www
    networks:
      - backend
  nginx:
    container_name: ${APP_NAME}-nginx
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./:/var/www
    networks:
      - backend
  db:
    container_name: ${APP_NAME}-db
    image: postgres:latest
    cap_add:
      - SYS_NICE
    networks:
      - backend
    volumes:
      - ./docker/db/db_data:/var/lib/postgresql/data
      - ./docker/db/dumps:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  redis:
    container_name: ${APP_NAME}-redis
    image: redis:latest
    restart: on-failure
    networks:
      - backend
    ports:
      - "6379:6379"
    command: "redis-server --appendonly yes --requirepass 123"
    volumes:
      - ./docker/redis/db_data:/root/redis
    environment:
      - REDIS_PORT=6379
  mailcatcher:
    restart: on-failure
    image: dockage/mailcatcher:0.9.0
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - backend

networks:
  backend:
    name: backend
